Fixing insufficiency in view statements
dovahcin/MusicPlayer pull request #8
Opened 2022-03-26 11:08 UTC by dovahcin

2022-03-26 14:18 UTC, rezaiyan commented on app/src/main/java/com/example/musicplayer/features/features/playlist/PlayListFragment.kt
> +        playListViewModel.fetchListForView(requireContext())
اصلا نباید به ویومدل کانتکست بدی!

2022-03-26 14:18 UTC, rezaiyan commented on app/src/main/java/com/example/musicplayer/features/features/playlist/PlayListFragment.kt
> +    private fun showMusics(musics: MutableList<Music>) {
نیازی نیست لیست Mutable باشه

2022-03-26 14:19 UTC, rezaiyan commented on app/src/main/java/com/example/musicplayer/features/features/playlist/PlayListFragment.kt
> +        binding.progressbar.isVisible = isLoading
این‌ها رو میتونی با ویو دیتا بایندینگ انجام بدی

2022-03-26 14:20 UTC, rezaiyan commented on app/src/main/java/com/example/musicplayer/features/features/playlist/PlayListViewModel.kt
> +    private val exceptionHandler = CoroutineExceptionHandler { _, throwable ->
یک BaseVieiwModel بساز و اینها رو منتقل کن اونجا. تا برای بقیه ViewModel ها هم ریوز بشه.

2022-03-26 14:22 UTC, rezaiyan commented on app/src/main/java/com/example/musicplayer/features/features/playlist/adapter/PlayListAdapter.kt
> +class PlayListAdapter(private val items: MutableList<Music> = mutableListOf()) : RecyclerView.Adapter<PlayListHolder>() {
بجای RecyclerView.Adapter از ListAdapter استفاده کن. بهینه تره.

2022-03-26 14:23 UTC, rezaiyan commented on app/src/main/res/layout/item_music_list.xml
> +                android:layout_width="@dimen/match_constraint"
match_constraint اسم خوبی نیست

2022-03-26 14:24 UTC, rezaiyan requested changes
هنوز فولدر‌های idea و build گیت ایگنور نشده

2022-03-27 19:14 UTC, dovahcin commented on app/src/main/java/com/example/musicplayer/features/features/playlist/PlayListFragment.kt
> +        playListViewModel.fetchListForView(requireContext())
چرا؟

2022-03-27 19:15 UTC, dovahcin commented on app/src/main/java/com/example/musicplayer/features/features/playlist/PlayListFragment.kt
> +        binding.progressbar.isVisible = isLoading
منظورت اینه تو xml?

2022-03-27 19:17 UTC, dovahcin commented
با اندروید استودیو اینارو ایگنور میکنم نمیدونم چرا باز میاد؟

2022-03-28 21:19 UTC, rezaiyan commented on app/src/main/java/com/example/musicplayer/features/features/playlist/PlayListFragment.kt
> +        binding.progressbar.isVisible = isLoading
آره، البته هر طور خودت مایلی.

2022-03-28 21:20 UTC, rezaiyan commented on app/src/main/java/com/example/musicplayer/features/features/playlist/PlayListFragment.kt
> +        playListViewModel.fetchListForView(requireContext())
اینجوری دیگه نمیتونه ViewModel رو با Unit test تست کنی!

2022-04-03 08:17 UTC, merged